#
# This file is part of the FlossWare family of open source software.
#
# FlossWare is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
#
---

- name: Install optware libraries
  yum:  name={{ item }} state=latest
  with_items:
  - ant
  - "@Development Tools"
  - git
  - subversion
  - cvs
  - java-1.8.0-openjdk
  - texinfo
  - m4
  - glibc-devel
  - flex
  - bison
  - yasm
  - libxml2-devel
  - ruby
  - intltool
  - unicode-ucd
  - rcs
  - gperf
  - python-mako
  - scons
  - itstool
  #- libxml2-utils
  - icon-naming-utils
  #- g++-multilib
  - doxygen
  - gdk-pixbuf2-devel
  - txt2man
  - xmlto
  #- xsltproc
  - libxslt
  #- docbook
  - docbook-xsl
  - asciidoc
  #- gcj-jdk
  #- libgcj-devel
  - cmake
  - ncurses-devel
  #- libx11-devel
  - fakechroot