---

- name: Install filesystem libraries
  yum:  name={{ item }} state=latest
  with_items:
    - autofs
    - cifs-utils
    - samba-client
    - nfs-utils

- name: Create auto.master
  template: src=auto.master.j2 dest=/etc/auto.master

- name: Create auto.host files
  template: src=auto.host.j2 dest="/etc/auto.{{ item.name }}"
  with_items: "{{ autofs_master }}"

- name: Ensure autofs is running
  service: name=autofs state=restarted enabled=true