---

#
# Setup security
#
- name: Set firewall state.  By default, stopped.
  service: name=firewalld state={{ firewall_state }}

- name: Set selinux to either enabled or disabled.  By default, disabled.
  selinux: state={{ selinux_state }}