---

- name: Update all
  yum: name=* state=latest

- name: Install virtualization
  yum:  name={{ item }} state=present
  with_items:
  - "@Virtualization"
  - libvirt
  - virt-manager
  - virt-install

- name: Ensure libvirtd is running
  service: name=libvirtd state=restarted enabled=true