#
# This file is part of the FlossWare family of open source software.
#
# FlossWare is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
#
---
#
# Enable port-forwarding
#
- name: Set packet forwarding if not present
  lineinfile: dest=/usr/lib/sysctl.d/50-default.conf state=absent line="net.ipv4.ip_forward = 1"

- name: Set packet forwarding if present
  lineinfile: dest=/usr/lib/sysctl.d/50-default.conf state=present regexp="^net.ipv4.ip_forward = 0" line="net.ipv4.ip_forward = 1"

- name: Invoke sysctl for packet forwarding
  command: /usr/sbin/sysctl -p